[package]
name = "assignment2"
version = "0.1.0"
authors = ["Martin Simensen <simensen94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.8.1"
gio = "0.8.1"
gdk-pixbuf = "0.8.0"
glib = "0.9.3"
