[package]
name = "genetic"
version = "0.1.0"
authors = ["Martin Simensen <simensen94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "genetic"
crate-type = ["cdylib"]

[dependencies]
approx = "0.3.2"

[dependencies.pyo3]
version = "= 0.8.5"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
